In [39]:
import numpy as np
# Tạo mảng
a = np.array([1,2,3,4,5])
# In mảng
print(a)

[1 2 3 4 5]


In [40]:
# In ra một phần tử bất kỳ
element = a[1]
print(element)

2


In [41]:
# Tạo mảng 2 chiều
matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(matrix)
# In một phần tử
my_element = matrix[1,2]
print(my_element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


# Cách tạo mảng 


In [42]:
# Tạo mảng toàn là số 0
a = np.zeros(5)
print(a)

# Tạo mảng toàn là số 1
a = np.ones(10)
print(a)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [43]:
# Tạo mảng rỗng
a = np.empty(5)
print(a)

[0. 0. 0. 0. 0.]


In [44]:
# Tạo mảng từ 0 đến 100
a = np.arange(100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [45]:
# Tạo mảng gồm các phần tử với khoảng cách đều nhau
a = np.linspace(0,10, num=5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [46]:
# Xác định kiểu dữ liệu
a = np.ones(5, dtype=np.int64)
print(a)
print(a.dtype)

[1 1 1 1 1]
int64


# Thêm, xóa, sắp xếp mảng

In [47]:
# Sắp xếp mảng
arr = np.array([5,8,1,9,2,4,10,3,7,6])
print(arr)
arr = np.sort(arr)
print(arr)
# Sắp xếp rồi đảo ngược
arr = np.sort(arr)[::-1]
print(arr)

[ 5  8  1  9  2  4 10  3  7  6]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [48]:
# Thêm phần tử vào mảng
arr = np.append(arr, 0)
print(arr)

[10  9  8  7  6  5  4  3  2  1  0]


In [49]:
# Xóa một vị trí nào đó trong mảng
arr = np.delete(arr, 5)
print(arr)

[10  9  8  7  6  4  3  2  1  0]


In [50]:
# Tạo mảng 2 chiều
 # Sắp xếp lại theo hàng
myarr = np.array([[3,1,2],
                  [6,4,5],
                  [8,7,9]])
sap_xep_theo_hang = np.sort(myarr, axis = 1) # axis = 1 nghĩa là sắp xếp theo hàng
print(sap_xep_theo_hang)

 # Sắp xếp lại theo cột
myarr = np.array([[3,1,2],
                  [6,4,5],
                  [8,7,9]])
sap_xep_theo_cot = np.sort(myarr, axis = 0) # axis = 0 nghĩa là sắp xếp theo cột
print(sap_xep_theo_cot)

 # Sắp xếp giảm dần
myarr = np.array([[3,1,2],
                  [6,4,5],
                  [8,7,9]])
sap_xep_giam_dan = -np.sort(-myarr, axis = 1)
print(sap_xep_giam_dan)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 1 2]
 [6 4 5]
 [8 7 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
# Sử dụng các thuộc tính để lấy thông tin mảng
arr = np.array([[1,2,3], [4,5,6]])
so_chieu = arr.ndim # (2 chiều)
kich_thuoc = arr.size # Kích t Số chiềuhước (tổng số phần tử, 6)
hinh_dang = arr.shape # Hình dạng (số hàng và số cột, (2,3))
print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [52]:
# Chuyển đổi kiểu dữ liệu
arr = np.array([1,2,3,4,5])
arr_float = arr.astype(float) # Chuyển từ số nguyên sang số thực
print(arr_float)

[1. 2. 3. 4. 5.]


In [53]:
# Thay đổi hình dạng của mảng
arr = np.array([1,2,3,4,5,6])
reshape_arr = arr.reshape(2,3) # 2 hàng, 3 cột
print(reshape_arr)
reshape_arr = arr.reshape(3,2) # 3 cột, 2 hàng
print(reshape_arr)
# Chuyển từ kết quả đã tạo ra từ mảng 2 chiều về mảng 1 chiều
reshape_arr = reshape_arr.flatten()
print(reshape_arr)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [54]:
# Cắt lát mảng
arr = np.array([1,2,3,4,5])
sub_arr = arr[1:4]
print(sub_arr) # kết quả là 2,3,4

sub_arr = arr[:-1]
print(sub_arr) # kết quả là 1,2,3,4

sub_arr = arr[-2:]
print(sub_arr) # kết quả là 4,5

[2 3 4]
[1 2 3 4]
[4 5]


In [55]:
# Chuyển vị mảng 
arr = np.array([[1,2,3], [4,5,6]])
print(arr)
# Để chuyển vị mảng chúng ta có thể sử dụng .T hoặc hàm numpy.transpose()
transpose_arr = arr.T
print(transpose_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [56]:
# Nối hay gộp mảng
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
new_arr = np.concat((arr1, arr2))
print(new_arr)

[1 2 3 4 5 6]


In [57]:
# Hàm tính tổng (Sum)
 # - Cho phép tính tổng các phần tử bên trong mảng.
arr = np.array([1,2,3,4,5])
total_array = np.sum(arr)
print("Tổng của mảng arr:", total_array)

# Hàm tính trung bình (Mean)
 # - Tính giá trị trung bình của các phần tử bên trong mảng.
arr = np.array([1,2,3,4,5])
average_array = np.mean(arr)
print("Giá trị trung bình của mảng arr:", average_array)

# Hàm tính giá trị lớn nhất (Max)
 # - Tìm giá trị lớn nhất bên trong mảng.
arr = np.array([1,2,3,4,5])
max_value = np.max(arr)
print("Giá trị lớn nhất của mảng arr:", max_value)
# Hàm tính giá trị nhỏ nhất (Min)
 # - Tìm giá trị nhỏ nhất bên trong mảng.
arr = np.array([1,2,3,4,5])
min_value = np.min(arr)
print("Giá trị nhỏ nhất của mảng arr:", min_value)

# Hàm tính độ lệch chuẩn (Standard Deviation)
 # - Tính phương sai của mảng, đo lường mức độ phân tán của dữ liệu.
arr = np.array([1,2,3,4,5])
std_deviation = np.std(arr)
print("Độ lệch chuẩn của mảng arr:", std_deviation)

# Hàm tính phương sai (Variance)
 # - Tính phương sai của mảng, đo lường độ biến thiên của dữ liệu.
arr = np.array([1,2,3,4,5])
variance = np.var(arr)
print("Phương sai của mảng arr:", variance)

# Hàm tính tổng chập (Dot Product)
 # (Chỉ tính được cho mảng 1 chiều)
 # - Tính tổng chập của hai mảng (vector).
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
dot_product = np.dot(arr1, arr2) #Cách tính: 1*6+2*7+3*8+4*9+5*10 = 130
print("Tổng chập của arr1 và arr2:", dot_product)

Tổng của mảng arr: 15
Giá trị trung bình của mảng arr: 3.0
Giá trị lớn nhất của mảng arr: 5
Giá trị nhỏ nhất của mảng arr: 1
Độ lệch chuẩn của mảng arr: 1.4142135623730951
Phương sai của mảng arr: 2.0
Tổng chập của arr1 và arr2: 130
